### ISSUE TITLE
Pass arguments to states?

### ISSUE THREAD

**Issue by ghost** [FrozenCanuck/Ki#10]
According to the API I can send arguments to an event:

```
mainStatechart.sendEvent("showView", sender, context)
```

But is it possible to send arguments to a state?

```
this.gotoState("SHOWING_VIEW", fromCurrentState, useHistory)
```

/Johnny

**Comment by FrozenCanuck** [comment]
On the current master branch, not at the moment. However, I have an experimental branch where you can pass a context argument to the `gotoState` function. Over the next week or two I plan on bringing this functionality over to the master branch.
