### ISSUE TITLE
initialSubstate: should not be required

### ISSUE THREAD

**Issue by erichocean** [FrozenCanuck/Ki#11]
The specification does not require an initial substate (you can been in a parent state without being in any substate) and a number of widely used statechart patterns require this behavior.

Ki should allow a state with substates to not define initialSubstate. Currently, it throws an error.

**Comment by FrozenCanuck** [comment]
Can you provide examples of where you do not need to define an initial substate?

**Comment by erichocean** [comment]
Nevermind, I'm making so many changes to Ki/SC.Statechart at this point, I'll just do it myself.
