### ISSUE TITLE
How do split the statechart into different files?

### ISSUE THREAD

**Issue by ghost** [FrozenCanuck/Ki#16]
Is it possible to split the statechart into different files?

Eg one for each state.

Thanks.

**Comment by ghost** [comment]
I know how know:

SHOWING_SIGNED_OUT_VIEWS: Ki.State.plugin("Main.SHOWING_SIGNED_OUT_VIEWS")

**Comment by FrozenCanuck** [comment]
Yep, that would be it :-)
