### ISSUE TITLE
Multiple history states for one state?

### ISSUE THREAD

**Issue by ghost** [FrozenCanuck/Ki#18]
I've read your wiki page about history states.

It seems that one state can hold one history state (the substate that was last entered) right?

Is it possible to "log" all states that were entered so it would be like a browser's BACK and FORWARD button, jumping through all states you have been in?

Because now it seems that I can only jump back ONE state.

**Comment by FrozenCanuck** [comment]
Yes, you can use recursive history by doing the following:

```
gotoHistoryState('fooState', YES);
```

The YES argument tells Ki to follow history states recursively until there are no more to follow.
