### ISSUE TITLE
Make isCurrentState et al observable

### ISSUE THREAD

**Issue by devinus** [FrozenCanuck/Ki#2]
Right now I can't make a binding to isCurrentState because it's not re-fired once the state does become the current state since it's just a .property().

**Comment by FrozenCanuck** [comment]
Agreed. Will be addressed

**Comment by FrozenCanuck** [comment]
Has now been addressed

**Comment by FrozenCanuck** [comment]
Made a mistake when calling a state's notifyPropertyChange method. See issue #3.
