### ISSUE TITLE
Does Ki works with Node.js?

### ISSUE THREAD

**Issue by ghost** [FrozenCanuck/Ki#22]
I wonder if Ki works with Node.js?

If it does, how do I include it?

Thanks.

**Comment by FrozenCanuck** [comment]
Not by itself since Ki requires SproutCore's runtime subframework to function. However, if the SC runtime can be injected into node.js, then, yes, you will then be able to use Ki.

Speaking of which, the ability to use statecharts in node.js is a great idea :-)

**Comment by ghost** [comment]
Yeah. Working with Node.js with no statechart is like coding spaghetti back in the days :)
