### ISSUE TITLE
How to dynamically add states?

### ISSUE THREAD

**Issue by ghost** [FrozenCanuck/Ki#28]
I'm using Ki with sproutcore where I'm having a lot of independent modules with their own states.

I wonder how I could dynamically add one module's states in the current statechart?

Thanks.

**Comment by FrozenCanuck** [comment]
Right now there is no kind of event forwarding feature to tie statecharts together as a more cohesive whole. Essentially you have to do your own binding to connect one statechart with another statechart. So if you have a statechart A with a current state and it receives an event `evt` that needs to be forwarded on to another statechart B, then that current state will have to explicitly call statechart B's sendEvent method and pass it `evt`.
