### ISSUE TITLE
isCurrentState still not observable

### ISSUE THREAD

**Issue by devinus** [FrozenCanuck/Ki#3]
With the latest Ki I must still notifyPropertyChange('isCurrentState') on my state's enterState/exitState to notify things bound to isCurrentState. It appears isCurrentState is still a .property() that doesn't observe anything:

```
isCurrentState: function() {
  return this.stateIsCurrentSubstate(this);
}.property()
```

**Comment by FrozenCanuck** [comment]
Sorry. I made a silly mistake when invoking a state's notifyPropertyChange method. The statechart is responsible for calling the state's notifyPropertyChange method. The isCurrentState computed property is now observable. All unit tested and working.

**Comment by devinus** [comment]
Awesome! Just trying to do my part with bug reporting. :)

**Comment by FrozenCanuck** [comment]
Bug reporting is more than welcome :-)
