### ISSUE TITLE
How to use it with Handlebars

### ISSUE THREAD

**Issue by plusgut** [FrozenCanuck/Ki#32]
Hi, how is Ki working with the new Sproutcore-Handlebars?

**Comment by FrozenCanuck** [comment]
Ki has been fully migrated over to SproutCore, so it is now under the SC namespace when you get the latest sproutcore code. As for the statechart logic, it works the same way as you would apply it to regular views prior to the template feature. No special extensions have been made at the moment.

**Comment by plusgut** [comment]
Thanks a lot.
