### ISSUE TITLE
Could Ki be used with ExtJS?

### ISSUE THREAD

**Issue by ghost** [FrozenCanuck/Ki#34]
Hi

I am using ExtJS and really miss the Ki framework.

Is there any change Ki could be used with ExtJS if I include the Sproutcore js files into the frontend?

/Johnny

**Comment by FrozenCanuck** [comment]
Hi Johnny,

Glad you liked using Ki, however, the current implementation of the framework is heavily tied with the SproutCore framework. There's no simple change to make Ki completely decoupled from SC. I've been playing around with the idea of making a pure JavaScript statechart framework, but for now it just remains an idea :-/.
