### ISSUE TITLE
Documentation and example apps?

### ISSUE THREAD

**Issue by ghost** [FrozenCanuck/Ki#6]
Will there be a more solid documentation soon on how to use it.

Would be great to read some tutorials and create some example apps.

**Comment by FrozenCanuck** [comment]
This has definitely been on my list of things to do. I'm hoping to start addressing this over the holidays. Kind of like a little nerdy Christmas present for all those who want to use statecharts.

**Comment by ghost** [comment]
I and a lot more would appreciate this Christmas present!

Good if you could document how to use all the advanced features like history, parallel states etc.

**Comment by FrozenCanuck** [comment]
Yep, those features are things I plan on documenting
